#!/bin/bash
echo "Enter first number: "
read X
echo "Enter second number: "
read Y
echo "The sum of $X and $Y is : " $((X + Y))
sleep 1
echo "The difference between $X and $Y is : " $((X - Y))
sleep 1
echo "The product of $X and $Y is : " $((X * Y))
sleep 1
echo "The quotient of $X amd $Y is : " $((X / Y)) 
